### ISSUE TITLE
Possibility of having more plasma species of same kind in plasma composition

### ISSUE THREAD

**Issue by Mateasek** [cherab/core#139]
Having the possibility to have more species of same kind with different Maxwellian distributions in plasma species would be a nice possibility.

It can happen that there are two populations of same species with different temperatures and densities, for example hot and cold hydrogen neutrals. Now it is impossible because species are stored in the Composition object as a dictionary with key made of tupple (element.key, species.charge). This results in overwriting an already existing species, if you are trying to and the same element with different distribution.

Having this possibility would be a benefit because a lot of species not in thermal equilibrium can be nicely treated with multiple Maxwellian distributions and this allows to use reaction rate constants from atomic databases.

**Comment by CnlPepper** [comment]
Hi @Mateasek,

the single species in the composition is intentional. The correct way to deal with this in the framework is to develop a new distribution object e.g  MultiMaxwellian() that consists of n-maxwellian distributions.

Models would need to be adapted to handle additional types of distribution explicitly, or rely on integrating the full distribution function (100% general, but slow).

To be truly general a model should:

1) be able to integrate the full distribution function
2) provide special optimisations for a maxwellian distribution (via effective temperature etc...)
3) provide specialisations and optimisations if other distribution types are detected.

At present most models only understand maxwellian distributions, rather than the full distribution function (mostly due to the adas data they use baking in that distribution). It was always intended to ultimately expand the models to cope with arbitrary distribution functions.

It would be best to have a conversation about this at some point.

**Comment by mattngc** [comment]
Hey @Mateasek,

Yeah I agree with Alex's view here. Your idea is sound, but I think you will find CHERAB has been design with supporting advanced distribution functions in mind. The problem is we have been a bit lazy with the emission models. As Alex points out, each model should explicitly check the underlying distribution function is appropriate and perform calculations as required. So far all our models are Maxwellian so we haven't needed to try this. You might be the first. Let's include this in the scope of our next Zoom meeting.

Matt

**Comment by Mateasek** [comment]
Making calculation on a full velocity distribution function is indeed a proper approach, although to me it sound quite computationally demanding and for many problems quite an overkill. Also for many processes you will need cross-sections for the reactions and those might be hard to get compared to reaction rates. This is one of the main reasons why I was suggesting having a possibility of adding a single species multiple times to plasma, it seemed to me as the easiest (and laziest) option. Maybe having a possibility of a multi-modal Maxwellian distribution?
