### ISSUE TITLE
Add Fiesta equilibrii as a supported Equilibrium type

### ISSUE THREAD

**Issue by mattngc** [cherab/core#164]
Some parties are interested in using Fiesta equilibria in CHERAB. In theory Fiesta has very descriptive data describing the modeled equilibrium. But at the moment the only way to use a Fiesta equilibrium would be to dump to an eqdsk file and then load again. It seems more natural to add an import function for Fiesta directly.

**Comment by Mateasek** [comment]
Does Fiesta has any standard file it saves the results to and does it have a constant format? Because I thought the only way of exporting Fiesta data is to save some matlab structure into a file (which if the right version is chosen is hdf5). This could be quite fluid format with need of a lot of updates. Also it could have a lot of machine/user specifics. I am pointing this out because I would also be interested in this feature.

How are you planning to do this? A separate package allowing some changes to cover possible machine/user specifics?

Maybe this could also initiate creating a more general equilibrium class which could support more sets of input data it could initiate itself from?

**Comment by mattngc** [comment]
Yes, the plan at the moment is to support a Fiesta matlab state file. So this would be a .mat binary file and can be quite large (>25mb!). At the moment I'm just planning to support some of the example files I've been given and then we can expand it from there based on user feedback and any errors reported.

I wasn't planning to make a separate package, as ideally this would just be an import_from_Fiesta() function. Maybe it would internally detect and deal with a few different file format versions but that is the extent of it.

And yes, in the longer version we need a more general equilibrium class. But I wouldn't group that with this issue.

**Comment by Mateasek** [comment]
When you are ready I can test it with the files we have for COMPASS and COMPASS Upgrade to see how "robust" it is, if you like.

**Comment by mattngc** [comment]
Yeah, that would be great. I'll get you to test the feature.

**Comment by mattngc** [comment]
Unfortunately it turns out there isn't a standard FIESTA file format. I'll keep this feature in the machine specific packages.
