### ISSUE TITLE
Segmentation Fault when plasma.b_field is not set

### ISSUE THREAD

**Issue by Mateasek** [cherab/core#231]
If b_field is not assigned to plasma, observation can end up in segmentation fault. I stumbled upon this problem when working with beams. This can be very difficult to track. Is this a behavior we want? 

`cdef VectorFunction3D get_b_field(self)` could raise an exception, if b_field equals to None or it could be set to zero vector on default to avoid repetitive value testing. Any other ideas about how this behavior could be avoided?

**Comment by jacklovell** [comment]
We definitely don't want segmentation faults! I can see in a couple of the models (lineshape and charge exchange) that no check is made for the B field being `None`:
https://github.com/cherab/core/blob/d58c8c26470209be9643a8c23b9dc9385bbe30e9/cherab/core/model/lineshape.pyx#L441

The declaration of `get_b_field()` promises the function will return a `VectorFunction3D` object. If it can't do this (because `self._bfield` isn't a `VectorFunction3D`) it should raise an exception, probably a `ValueError`. Calling code should then handle the exception if it is able to continue on without the B field, otherwise the exception should be allowed to propagate.

**Comment by CnlPepper** [comment]
The b_field should never be None. The plasma object should modified to prevent it being None, defaulting to a constant function of zero field. I'm not sure why I missed this when re-implementing the plasma object... the change needs to go here: https://github.com/cherab/core/blob/d58c8c26470209be9643a8c23b9dc9385bbe30e9/cherab/core/plasma/node.pyx#L352

Just a reminder: the cython interface deliberately provides minimal checks to provide good performance in the inner loop. All checks should ideally be performed at initialisation, not during calculation Adding a None check inside each model is the wrong way to address this issue as it'll slow down execution under certain circumstances. If you ever feel the need to add a check for existence in an inner loop path, then something else is probably wrong - fix that instead.

**Comment by jacklovell** [comment]
Good point. Note also that `self._bfield` is set to `None` in `__init__`, bypassing this setter. That needs fixing too.

**Comment by Mateasek** [comment]
This is what i meant by repetitive value testing. b_field can be called frequently by models and numerical integrators. I will make a fast fix and set the b_field to zero vector.

**Comment by Mateasek** [comment]
Looking into the plasma __init__ there are other attributes with None value after the initialisation: _electron_distribution, _atomic_data, _geometry, _geometry_transform this could all lead to similar problems, couldn't it? Wouldn't it be better to set the parameters to some default values? e.g.:

_electron distribution: Zero density and temperature 1 eV
_atomic_data: Here we could on default set OpenADAS, since we have no other source ready
_geometry: Here we could use a Primitive instance? This willl raise Nonimplementederrors in the tracer
_geometry_transform: Identity transform?

**Comment by jacklovell** [comment]
I'm a fan of this: all these properties have defined extension types in the corresponding pxd file, so setting them to `None` is technically incorrect. They won't cause the same segmentation fault problem as the B field, as none of them have fast cython accessor methods: all are accessed using Python `@property` syntax instead, which can cope with `None` instead of the type which was promised. But for pure correctness they should be fixed, particularly as it seems pretty simple to do. I agree with the suggestions for default values too, but defer to @CnlPepper for the final say.

**Comment by CnlPepper** [comment]
Btw None is a perfectly valid value for an extension typed property, it is not technically incorrect. None is often used to represent that the user has no preference and the code should use a default, for example.

**Comment by CnlPepper** [comment]
...in fact I would use None in the electron_distribution setter as a way of setting the electron_density back to the default of a ZeroDistribution().

**Comment by Mateasek** [comment]
Ok, compiling what was suggested here I wil:

I will create a new distribution ZeroDistribution which will return zero scalars/vectors by the class methods and I will assign this ZeroDistribution to the _electron_distribution in the setter if None is passed.

I will assign zero vector to the b_field setter in the plasma init.

Thanks for the explanations

**Comment by Mateasek** [comment]
fixed with PR #232
