### ISSUE TITLE
OpenADAS geting a wrong beam population rates

### ISSUE THREAD

**Issue by Daniel-ler** [cherab/core#252]
I found a possible issue in openADAS, running the [example](https://cherab.github.io/documentation/demonstrations/atomic_data/beam_plasma_interactions.html#beam-plasma-interaction-rates) on the CHERAB website, gives me different beam population rate result than presented there. 
When I run the example code i get rate ~10^-9: 
![image](https://user-images.githubusercontent.com/77324114/104916846-e52d9880-5992-11eb-8225-8db5598277a7.png)
In the plot from the [example](https://cherab.github.io/documentation/demonstrations/atomic_data/beam_plasma_interactions.html#beam-plasma-interaction-rates) it's ~10^-3, which makes 10^6 difference, that could be unit conversion cm^3/m^3, but I am not sure as the final values are dimensionless. 
I checked the literature, the 10^-3 values are in the correct order of magnitude.
So, it seems it worked when the example was made, but does not now, at least when I run it.

**Comment by Mateasek** [comment]
Cherab works in m^3/s, so I think you are right that the order difference comes from the units. Maybe the picture was made before the Cherab unit system settled down.

Also, it shouldn't be dimensionless but has the mentioned m^3/s unit, or am I wrong?

Last thing is that the example does not run without errors on the development branch, we have to update some function names.

**Comment by vsnever** [comment]
Hi @Mateasek, 

I may be wrong, but I think there is actually a bug here. If I understand this correctly, beam population is a ratio of beam atoms in the excited state to the beam atoms in ground state, and thus it should be a dimensionless value. However, all adf21 and adf22 ADAS data files are parsed using the same `parse_adas2x_rate()` function from [cherab/openadas/parse/utility.py](https://github.com/cherab/core/blob/master/cherab/openadas/parse/utility.py). This function converts the beam stopping rate (adf21) or beam emission coefficient (adf22, bme) from cm3 s-1 to m3 s-1. In case of beam population (adf22, bmp), the respective parameter ("SV" in ADAS notations and "sec" in Cherab notations) is a dimensionless one and should not be converted. @mattngc and @jacklovell, could you please check if I'm right or not?

**Comment by vsnever** [comment]
Also, this demo should be moved from docs/source/demonstrations/atomic_data/beam_plasma_interactions.rst to a separate Python script in demos folder.

**Comment by CnlPepper** [comment]
It is entirely possible that an error crept in a few years ago when I was redesigning and refactoring the openadas package. 

The only info on the OpenADAS page is as follows:
https://open.adas.ac.uk/man/appxa-21.pdf
https://open.adas.ac.uk/man/appxa-22.pdf

This indicates BME and BMS are both density dependent according to the units listed. BMP... I honestly can't remember as it has been too long.

**Comment by vsnever** [comment]
@CnlPepper, yes, BMP are not documented in ADAS as if they did not exist. There is also an ambiguity within Cherab, the `AtomicData.beam_population_rate()` states that it returns "beam population coefficients in m^3/s" while the `BeamPopulationRate` class states that this is a dimensionless "relative beam population of excited state over ground state". I think, the latter makes more sense, and if it's also true, then we should modify the `parse_adas2x_rate()` by adding a boolean argument `bmp`, for example.

**Comment by CnlPepper** [comment]
I was just chatting to @mattngc about the cherab docs, we think the cherab docs here are incorrect. So in effect there are two bugs, one docs, one parser. The docs were written a lot later than the original code... and honestly we didn't have the resources to validate everything at the time.

If it turns out the BMP normalisation is broken, it is a relatively trivial fix. We just need to add an argument to the parse_adas2x_rate() that specifies the normalisation value and then update the individual adf install routines to set the correct normalisation.

**Comment by CnlPepper** [comment]
The CX beam code path has been unused for a while, neither @mattngc nor myself have used it for any research activities since it was refactored.

**Comment by Daniel-ler** [comment]
Hi,

I believe @vsnever is correct,  beam population rate is a ratio  density of excited state over the ground state  n(m)/n(1), giving it no dimension.  When I cross checked with some [literature](https://iopscience.iop.org/article/10.1088/0741-3335/44/1/307/pdf) I get correct values after taking into account the additional 10^-6 factor (that's my fix for now).  You are also correct about the docs. 

Thank you for clarifying.

**Comment by vsnever** [comment]
So, the fix for this would be:

1. Add `normalisation` argument to the `parse_adas2x_rate()` add apply it to 'SV', 'SVT' and 'SVREF',
2. Update `parse_adf21()`, `parse_adf22bme()` to call `parse_adas2x_rate(file, normalisation=Cm3ToM3)` and `parse_adf22bmp()` to call `parse_adas2x_rate(file, normalisation=1)`,
3. Fix `AtomicData.beam_population_rate()` docstring (m^3/s to dimensionless),
4. Fix `BeamEmissionPEC` docstring in core/atomic/rates (dimensionless to W m^3),
5. Move this example from beam_plasma_interactions.rst to a separate script in demos/openadas and replace deprecated `beam_cx_rate` with `beam_cx_pec`.

Is that all, or am I missing something?

@CnlPepper, @mattngc, if you have not started fixing this yet, I can do it.

**Comment by Mateasek** [comment]
@vsnever could we wait a bit?  I am still not fully convinced you are right. Since this has some consequences to BeamModels I've been working with intensively lately, I would like to have something more than a graphical comparison to an article as a proof. Although I haven't find anything about the beam population coefficient in the ADAS documentation, it is still bundled together with effective emission coefficients. Why would ADAS bundle it together and leave out any visible remark about there being two quantities in a single data type?

I always thought population coefficient is a rate by which excited beam populations are generated from the ground states by collisions with particles. Each plasma particle population should be taken into account with its density in this calculation. This is exactly what is being done in the BeamCXLine calculation, or at least this is my impression after looking into it shortly. This suggests the plasma population rare coefficient should have units m^3.

**Comment by vsnever** [comment]
@Mateasek of course. I've never worked on beam spectroscopy, so I'm not sure if I'm right either. The only thing we know for sure now is that there is an inconsistency in Cherab documentation.

**Comment by Mateasek** [comment]
I sent a question to OPEN ADAS, lets see if they can provide us with some clarifications. I haven't seen anything in none of the documentation they have ( code descriptions, file descriptions, documentation). We will see if they reply.

**Comment by vsnever** [comment]
> I sent a question to OPEN ADAS, lets see if they can provide us with some clarifications. I haven't seen anything in none of the documentation they have ( code descriptions, file descriptions, documentation). We will see if they reply.

Great, I was also thinking about that. We can also write to ADAS support or Dr Martin O'Mullane himself, if they do not reply.

**Comment by CnlPepper** [comment]
It's a bug. I found the original code: https://github.com/cherab/openadas/blob/ee83d2cc84b1b55e1e6c6fe1873941922de27a57/cherab/openadas/rates/beam.pyx

The BMP is not normalised. I must have introduced the bug during a refactor a few years ago. @vsnever if you are happy to make the change, please do.

**Comment by CnlPepper** [comment]
@Mateasek the ADAS file formats are an utter mess. They reuse the same structure for unrelated data. It was, and is, terrible design.

**Comment by CnlPepper** [comment]
> So, the fix for this would be:
> 
> 1. Add `normalisation` argument to the `parse_adas2x_rate()` add apply it to 'SV', 'SVT' and 'SVREF',
> 2. Update `parse_adf21()`, `parse_adf22bme()` to call `parse_adas2x_rate(file, normalisation=Cm3ToM3)` and `parse_adf22bmp()` to call `parse_adas2x_rate(file, normalisation=1)`,
> 3. Fix `AtomicData.beam_population_rate()` docstring (m^3/s to dimensionless),
> 4. Fix `BeamEmissionPEC` docstring in core/atomic/rates (dimensionless to W m^3),
> 5. Move this example from beam_plasma_interactions.rst to a separate script in demos/openadas and replace deprecated `beam_cx_rate` with `beam_cx_pec`.
> 
> Is that all, or am I missing something?
> 
> @CnlPepper, @mattngc, if you have not started fixing this yet, I can do it.

@vsnever  I was meant to also say: yes this is correct. :) I hope you don't mind me assigning it to you, if you don't have time I can fix it later this week.

**Comment by CnlPepper** [comment]
One thing everyone will need to be aware of: this issue lies in the repository population methods, so any existing data in your local cherab rate repositories will need to be purged and regenerated. If this is not done, the old, incorrectly processed values will still be present. **Don't forget to rebuild your atomic data repositories!**

**Comment by vsnever** [comment]
@CnlPepper, I'll fix this. I am currently checking other documentation pages with reference to beam rates.

**Comment by CnlPepper** [comment]
Some more useful info can be found in the documentation of the adas python routines:

https://www.adas.ac.uk/python_lib/read_adf21.html
https://www.adas.ac.uk/python_lib/read_adf22.html

The adf22 reader returns dimensionless or ph cm**3/s depending on the file type:

```
Returns
    coeff : float, array
    total effective beam emissivity coefficient (ph cm3 s-1) or fractional population (dimensionless).
```

**Comment by vsnever** [comment]
There are other inconsistencies with dimensions. The docstring for `BeamCXRate` says that it's in [photon m3 s-1 ster-1] but it looks like it's in [W m3].

**Comment by CnlPepper** [comment]
I'm mystified how these are now incorrect. They were correct in the original release code: https://github.com/cherab/openadas/blob/ee83d2cc84b1b55e1e6c6fe1873941922de27a57/cherab/openadas/rates/cx.pyx

I'm guessing the documentation was incorrectly copied from the ADAS docs, not the source code.

**Comment by CnlPepper** [comment]
If in any doubt I recommend looking the code from the original core and openadas package source releases. These codes were validated at JET prior to release.

**Comment by CnlPepper** [comment]
The framework has been victim to a lack of unit testing due to limitations on human resource. New features have led to refactors/rewrites, which have led to a few bugs creeping in where existing codepaths have not been in active use (ie. beams + CX). Something we will need to address if anyone has spare resources or can acquire them. We should raise this as a topic at the next cherab meeting.

**Comment by vsnever** [comment]
Here: https://cherab.github.io/documentation/atomic/rate_coefficients.html#cherab.core.atomic.rates.BeamCXRate it says [photon m3 s-1 ster-1], in the `BeamCXRate` docstring it's [W m3 s-1 ster-1] and in openadas/rates/cx.py it's [W m3] :). The latter is correct.

**Comment by CnlPepper** [comment]
Yeah that definitely needs fixing, thanks for spotting it.
