### ISSUE TITLE
Error when calling beam_emission_pec(...)

### ISSUE THREAD

**Issue by Daniel-ler** [cherab/core#259]
Hi, I think there might be possible issue in: _core/cherab/openadas/openadas.py_  
function - `beam_emission_pec(self, beam_ion, plasma_ion, charge, transition)`   - line 218.
I don't exactly understand everything that's happening in the code, so just bear with me : 
the Function call could look like this : `beam_emission_pec(Deuterium, Deuterium, 1, (3,2))`
When I do this everything works fine, I get what I believe is correct rate....
issue begins when I try to call `beam_emission_pec(Deuterium, Carbon, 6, (3,2))` then it says something like: 
_Requested wavelength (element=C, charge=5, transition=(3, 2)) is not available._

So I checked the ADAS database and this rate should be available, also, I checked local files and it was present.  
then I found that in the  `beam_emission_pec(self, beam_ion, plasma_ion, charge, transition)` 
at line 218: ` wavelength = repository.get_wavelength(plasma_ion, charge - 1, transition)`  
there is a call for wavelength, but I think it has wrong arguments, I would imagine it should look like this instead ` : 
wavelength = repository.get_wavelength(beam_ion, 0, transition)`

-as the emission is from the beam particle not the plasma. it fails at trying to get the wrong wavelength which is not present.
-also that's why the `beam_emission_pec(Deuterium, Deuterium, 1, (3,2))` works, by chance they are the same. 

But, maybe I am totally off here, because when using _core/cherab/core/model/beam/beam_emission.pyx_
I think the class `BeamEmissionLine(BeamModel)` also does the `beam_emission_pec` calls for all the plasma species,
but there seems to be no error when running, even with carbon 6 in the plasma. 

I would be grateful for any clarification on this.

**Comment by Mateasek** [comment]
Hi @Daniel-ler 

thank you for reporting this. I think you isolated the bug correctly. You are correct that because it is the beam particle radiating, the get_wavelength method should get beam ion species and charge, not the plasma one. I think this smuggled itself from the CX collisions. I quickly applied the fix `repository.get_wavelength(beam_ion, 0, transition)` you suggested and it seems it is a 'hot fix' you can use in your repo.

The error does not happen only if the species are the same and the plasma species has charge 1 higher than the beam. This is why it is not happening for the case `beam_emission_pec(Deuterium, Deuterium, 1, (3,2))`

To fix this properly, I think there should be both charges of the beam and plasma particles passed to the method `beam_emission_pec`. It would be more general. Any other ideas anybody (@vsnever and @CnlPepper)?

**Comment by Mateasek** [comment]
Just for the information [this](https://github.com/cherab/core/blob/11ef1ac9072cc20803c953aca98ab8051e76790f/cherab/core/model/beam/beam_emission.pyx#L157) is how the `BeamEmissionLine` gets the wavelength.

**Comment by vsnever** [comment]
Hi @Daniel-ler, @Mateasek,

Looks like this process was mixed up with charge exchange. Yes, `repository.get_wavelength(beam_ion, 0, transition)` is a correct fix. I think that it is not necessary to pass the charge of a beam particle, because in ADAS there are no data for ionised beams as it is focused on NBI (just like other beam rates).

**Comment by CnlPepper** [comment]
This is one for @mattngc, he wrote the original code. It is not an area I have enough familiarity with. It looks like the wavelength is used to convert the photon count to watts in the BeamEmissionPEC rate class. On first look, I agree this looks incorrect.

**Comment by CnlPepper** [comment]
I had a look at the ADAS documentation for the BME data. This does look like a bug. The emission is from the beam therefore the photon/s to Watts conversion should use the wavelength for the beam ion, not the plasma ion. Be careful with setting the charge to 0 though. If it is a helium beam this won't necessarily be correct.

**Comment by vsnever** [comment]
The ADAS manual says "Only data for neutral beam species is present in the central ADAS database at this time". So, I think it's ok for Cherab to support only neutral beams for now. But if you decide to add beam charge, all interfaces related to beams will have to be updated.

**Comment by Mateasek** [comment]
I think adding the beam particle charge parameter to the `beam_emission_pec` method would make it more general. We now have only OpenADAS database, but the idea is to support arbitrary databases, even user defined. For this reason I think it would be beneficial, because in theory there can be beams of charged particles. `beam_emission_pec` is used only in three files, so there will not be so much work connected to this change. Lets wait for @mattngc.

**Comment by vsnever** [comment]
Of course, adding the beam charge is quite doable, but the change will be more complex than just `beam_emission_pec`. The following methods will have to be updated:

- `beam_stopping_rate`, `beam_population_rate` and `beam_emission_pec` in `AtomicData` and `OpenADAS` classes;
- `get_beam_*_rate`, `add_beam_*_rate`, `update_beam_*_rates` in `openadas.repository`, where * is `stopping`, `population` and `emission`;
- `populate` in `openadas.repository`;
- `install_adf21`, `install_adf22bmp` and `install_adf22bme` in `openadas`;
- `parse_adf21`, `parse_adf22bmp`, `parse_adf22bme` in `openadas.parse`.

The path to json files in the local repository, which is `beam/emission/{beam_species.symbol}/{target_ion.symbol}/{target_charge}.json`, will have to be corrected to `beam/emission/{beam_species.symbol}/{target_ion.symbol}/{beam_charge}-{target_charge}.json`.

**Comment by Mateasek** [comment]
You are right, I didn't realise that you will have to propagate the change to all the beam related atomic data and methods/classes. Still, it might be less painful now than later.

**Comment by mattngc** [comment]
Hi guys, sorry for being slow to the party here, been snowed under as usual. Thanks @Daniel-ler for spotting this, it does indeed look like a copy-paste bug I would have made when writing the original code. I suspect I was basing it off of one of the other emission models. This fix should be quite fast to implement.

Regarding supporting beam charges other than zero, I originally wrote this for use with ADAS data, hence not supporting the beam charge specification. There are other groups such as the Hungarians developing more general beam emission models with customised atomic data. I did some previous experiments with them but their atomic calculations used a different interface to ADAS, it wasn't easy to marry together their models with ADAS like rates. Instead, it was easier to make a custom emission model based of the original ADAS ones.

If @vsnever or @Mateasek would like to generalise these functions to support non-neutral beams, I won't object. But I don't think it is worth doing at this stage unless you have an atomic data source that can use it. Happy to accept a quick fix PR.
