### ISSUE TITLE
Switch to new Raysect interpolators

### ISSUE THREAD

**Issue by vsnever** [cherab/core#303]
When new interpolators are added to Raysect (see raysect/source#393), they should replace the existing Cherab interpolators in the Cherab code. This will solve #233 and slightly improve overall performance.

Here are the classes, functions and demo scripts that need to be updated:

1. `cherab.core.model.attenuator.SingleRayAttenuator`
2. `cherab.openadas.rates.cx.BeamCXPEC`
3. `cherab.openadas.rates.beam.BeamStoppingRate`
4. `cherab.openadas.rates.beam.BeamPopulationRate`
5. `cherab.openadas.rates.beam.BeamEmissionPEC`
6. `cherab.openadas.rates.pec.ImpactExcitationPEC`
7. `cherab.openadas.rates.pec.RecombinationPEC`
8. `cherab.openadas.rates.atomic.IonisationRate`
9. `cherab.openadas.rates.atomic.RecombinationRate`
10. `cherab.openadas.rates.atomic.ThermalCXRate`
11. `cherab.openadas.rates.radiated_power.LineRadiationPower`
12. `cherab.openadas.rates.radiated_power.ContinuumPower`
13. `cherab.openadas.rates.radiated_power.CXRadiationPower`
14. `cherab.tools.equilibrium.efit.EFITEquilibrium`
15. `cherab.tools.plasmas.ionisation_balance.interpolators1d_fractional()`
16. `cherab.tools.plasmas.ionisation_balance.interpolators2d_fractional()`
17. `cherab.tools.plasmas.ionisation_balance.interpolators1d_from_elementdensity()`
18. `cherab.tools.plasmas.ionisation_balance.interpolators1d_match_plasma_neutrality()`
19. `cherab.tools.plasmas.ionisation_balance.interpolators2d_from_elementdensity()`
20. `cherab.tools.plasmas.ionisation_balance.interpolators2d_match_plasma_neutrality()`
21. `demos/equilibrium/equilibrium.py`
22. `demos/plasmas/ionisation_balance_1d.py`
23. `demos/plasmas/ionisation_balance_2d.py`

Also the mappers `IsoMapper2D` and `IsoMapper3D` refer to `Interpolate1DCubic` in their docstrings.

The new Raysect interpolators lack the following features of Cherab interpolators:

 A. Optional support for length 1 arrays.
 B. Quadratic extrapolation for cubic splines in 2D and 3D cases.
 C. Continuity of second derivative in 1D cubic spline (default option in `Interpolate1DCubic`).
Also cubic splines in Raysect and Cherab interpolate data at edge intervals differently (quadratic in Cherab vs cubic in Raysect).

Feature A is used in the items 2 - 5.
Feature B is used in the items 3 - 13.
Feature C is used in the items 2 - 5, 14, 21 - 23.

I suggest the following solution:

- Check for length 1 arrays in the items 2 - 5 explicitly and use `Constant1D` in 1D case and custom function wrappers in 2D case.
- Replace quadratic extrapolation with the nearest neighbour method or ask to add this feature in raysect/source#393 (?).
- Drop feature C. It should be used with caution anyway in case of sharp features in the data arrays.

Should we add deprecation warnings to Cherab interpolators? 

Also replacing the Cherab cubic interpolators with the Raysect ones in the item 23 causes `lsq_linear()` to freeze in `cherab.tools.plasmas.ionisation_balance_fractional_abundance_point()`. This does not happen with Cherab interpolators even if `continuity_order` is set to 1. Switching to linear interpolation for 1D data in the item 23 solves the problem.

I'll create a draft pull request with the changes I've already made to test the new Raysect interpolators.

**Comment by CnlPepper** [comment]
I'd recommend not switching from quadratic to nearest neighbour, at the very least switch to linear extrapolation otherwise the various rate functions will not taper off to zero at the end of their ranges (resulting in significant rate value were it should be close to zero).

Simon was intending to add quadratic 2D/3D at some point, however we do not need it for our internal application at present. We will probably revisit the interpolators at a later date.

Similarly the 2nd order 1D is missing as we do not have a use for it at present. It and a constrained cubic option could be added later. The raysect interpolator framework is a lot easier to extend than the version in cherab.

The 1 element array feature was not replicated in the raysect interpolators as we felt the user should be aware that data does not meet the minimum requirements for a selected interpolation scheme. It means a few checks for some of the ADAS rates inits, but it should make it clearer to developers working on the code that 1 element data is handled a specific way.

**Comment by jacklovell** [comment]
Fixed in #304
