### ISSUE TITLE
Add TargetedPixelGroup

### ISSUE THREAD

**Issue by skuba31** [cherab/core#325]
Similar to the OpticalFiberGroup, this class could be used for photodiodes with pinholes or collimators. Typical use case would be AXUV photodiode arrays with pinhole that are often used as fast bolometers on tokamaks.

**Comment by vsnever** [comment]
Thanks for the idea, @skuba31.

In terms of implementation, the current version of `Observer0DGroup` is actually `SpectroscopicObserver0DGroup` because it only works with `SpectroscopicObserver0D` from Cherab, so we will need to rename it. The new `Observer0DGroup` should work with basic 0D observers from Raysect. Then inheritance will be as follows:

`Observer0DGroup(Node)`
`SpectroscopicObserver0DGroup(Observer0DGroup)`
`FibreOpticGroup(SpectroscopicObserver0DGroup)`
`SightLineGroup(SpectroscopicObserver0DGroup)`
`TargetedPixelGroup(Observer0DGroup)`

**Comment by Mateasek** [comment]
You could also include the regular pixel, which would make the non-imaging group complete, except the mesh observers, where this doesn't make much sense.

**Comment by skuba31** [comment]
Thanks for the breakdown @vsnever . @Mateasek I will include PixelGroup as well.

**Comment by jacklovell** [comment]
Fixed in #332
