### ISSUE TITLE
Missing top-level `__init__.py` file

### ISSUE THREAD

**Issue by munechika-koyo** [cherab/core#389]
I noticed the top-level `__init__.py` file (`cherab/__init__.py`) disappeared when composing making wheel file or after installing `cherab` using pip from github directory.

Top-level `__init__.py` file is always required for other package when it loads `cherab`'s cython `.pxd` files.

I think it is due to the `pkg_resource` style namespace package.
So, `pkgutil` style namespace package might resolve this issue.

**Comment by jacklovell** [comment]
The `__init__.py` file is not required at all for modern namespace packages, and wheel installations should work fine without it (they do on the several installations I manage). The file in the repository is a hangover from before PEP 420 support was widely available: easy_install-based installations using `python setup.py install` for example at one point required an `__init__.py`, as did `setup.py develop` if I remember correctly.

Cython imports are a separate issue, since pxd files are not used by Python imports. There is a [bug](https://github.com/cython/cython/issues/2918) in Cython which means namespace packages are not found when compiling pyx and pxd files which depend on a namespace package unless it has an `__init__.py`. The fix for this is to update to Cython 3.0a5 or later, and is only required at build time (not when installing pre-built wheels of the package in question).

**Comment by munechika-koyo** [comment]
Thank you for your early comment! @jacklovell 

As you mentioned, I know PEP420 namespace rule, but I did not it cause a bug for cython.
I cannot wait for Cython3.0! :)

**Comment by jacklovell** [comment]
> I cannot wait for Cython3.0! :)

Same: this build issue keeps coming up with Cherab users. We work around it in `cherab-solps` by requiring Cython 3.0a5 in that project's [pyproject.toml](https://github.com/cherab/solps/blob/a13b00eca5c71e0a15649c86ddc58cc11da609ad/pyproject.toml). You could consider doing the same.

There was a pull request to backport the PEP420 fix to Cython 0.29, but sadly it was rejected. So we're stuck waiting for a stable version of Cython 3.0 to come out.
