### ISSUE TITLE
Should ToroidalVoxelGrids default to CSG primitives?

### ISSUE THREAD

**Issue by mattngc** [cherab/core#83]
When testing on computers with lower system resources (i.e. laptops) I've noticed its extraordinarily easy to run into memory limits and crashes. We originally favoured the Mesh representation because it scales computationally better for cases with reflections. But @jacklovell noticed this representation can quickly lead to memory issues when dealing with high resolution voxel grids. He contributed an alternative CSG representation in #56. It now seems more sensible to default to this CSG representation and allow expert users to select the Mesh representation when required.

**Comment by jacklovell** [comment]
The downside to the CSG representation as it currently stands is that it is more computationally intensive. As I understand it, this is because in the general case the CSG representation uses the intersection of cones and cylinders to form voxel subelements with triangular cross sections, and then builds any arbitrary polygon shape out of the union of these sub-elements. The cones used may have large heights, and therefore large bounding spheres, which compromises the efficiency gains achieved by using a KD tree for the ray intersections.

I've already included some optimisations for when a voxel has a rectangular cross section aligned with the r and z axes, by building the voxel out of the subtraction of 2 cylinders. This reduces the number of primitives in the CSG, and eliminates the use of cones, which I think makes the bounding box smaller. In any case, this cylinder-subtraction formulism is significantly quicker than then union-of-triangular-elements formalism for high-voxel-count grids, but potentially still rather slower than a mesh-based formulism (assuming the latter can fit into memory).

If we do want to make the CSG representation the default, we should work to minimise the performance penalty for problems which do fit into memory already, otherwise users may consider this a performance regression. It'll take somebody with a better knowledge of the KD tree and how the bounding spheres in raysect are produced to provide sensible ideas for this.

I'm not aware of any other limitations the CSG representation has compared with the mesh representation, so this change shouldn't break any user codes. But again, it would be worth double checking this.

**Comment by mattngc** [comment]
I think this all depends on the complexity of the primitives in question. Its difficult to make general statements about their speed, it very much depends on the case in question.

Simple primitives e.g. Box, Cylinder, Sphere, etc, will always be faster than the others because their ray intersections are calculated analytically. Simple CSG operations, e.g. Box - Sphere are likely to be faster than meshes, especially when the triangle count in the Mesh is > 10.

In this particular case, whilst the CSG Voxel is made up of a few CSG operations, each Mesh AxisymmetricVoxel is made up of 1000s of smaller meshes. This leads to a much larger KD-Tree but the bounding spheres of each mesh element are much smaller. So although there are many more KD-Tree operations, this leads to much faster calculations of reflected light when using importance sampling. Its a trade off of one type of speed VS another.

I did some example tests for both types on my laptop using an AUG voxel grid of 2206 voxels. This was consuming several GB of RAM and causing the laptop to struggle. The CSG equivalent had a tiny memory footprint and was much faster. Hence I'm thinking its better to default to the CSG representation and only move to the Mesh representation when doing reflection calculations  on machines with large amounts of RAM. In the current configuration its too easy to accidentally reach a memory limit when experimenting with the code on an under-powered PC.

**Comment by mattngc** [comment]
Resolved with PR #137.
